# Generated by Django 6.0.3 on 2026-04-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_purchase_payment_method_invoice_sale_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('card', 'Card')], max_length=20),
        ),
    ]
