# Generated by Django 6.0.3 on 2026-03-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
