# Generated by Django 6.0.3 on 2026-04-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='expiry_date',
            field=models.DateField(default='2027-12-31'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('cash', 'Cash'), ('card', 'Card')], max_length=20),
        ),
    ]
