# Generated by Django 6.0.3 on 2026-04-07 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_purchase_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('cash', 'Cash'), ('card', 'Card')], max_length=20),
        ),
    ]
