# Generated by Django 6.0.3 on 2026-04-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_invoice_subtotal_invoice_tax_invoice_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='data',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('card', 'Card')], max_length=20),
        ),
    ]
